version: 1.0.{build}
build_script:
- cmd: nuget pack elmah.io.apps.azureboards.nuspec -Version %appveyor_build_version%
test: off
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: zW5wpse6lUxytGy97A4zTL4QmmIy0+Xws97OQsbxBYL69HUUnO73vlaGKd6A8Nzo
  artifact: /.*\.nupkg/